version: '3.8'

services:
  nextjs-app:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ML_SERVICE_URL=http://ml-service:8000
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      ml-service:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
    volumes:
      - ml-models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  ml-models:
    driver: local